name: My Project

options:
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true
  indentWidth: 4
  tabWidth: 4
  bundleIdPrefix: "com.manhpham"

targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources: [Sources]
    settings:
        INFOPLIST_FILE: Sources/Resources/Info.plist
        SWIFT_VERSION: "5.0"
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Resources/MyApp-Bridging-Header.h
        CODE_SIGN_STYLE: "Manual"
