name: My Project

configs:
    Debug: debug
    Staging: release
    Release: release

configFiles:
    Debug: Sources/Configs/BuildConfigurations/Debug.xcconfig
    Staging: Sources/Configs/BuildConfigurations/Staging.xcconfig
    Release: Sources/Configs/BuildConfigurations/Release.xcconfig

options:
    createIntermediateGroups: true
    groupSortPosition: top
    generateEmptyDirectories: true
    indentWidth: 4
    tabWidth: 4
    bundleIdPrefix: "com.manhpham"
    developmentLanguage: ja

settings:
PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)

targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: 
      - Sources
      - path: R.generated.swift
        optional: true
    attributes:
      SystemCapabilities:
        com.apple.Push:
          enabled: 1
    configFiles:
        Debug: Sources/Configs/BuildConfigurations/Debug.xcconfig
        Staging: Sources/Configs/BuildConfigurations/Staging.xcconfig
        Release: Sources/Configs/BuildConfigurations/Release.xcconfig
    settings:
        INFOPLIST_FILE: Sources/Resources/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Resources/App-Bridging-Header.h
        CODE_SIGN_ENTITLEMENTS: Sources/Resources/App.entitlements
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: "Manual"
        TARGETED_DEVICE_FAMILY: 1
    prebuildScripts:
        - name: R.swift
          script: |
            "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift"
          inputFiles:
            - $TEMP_DIR/rswift-lastrun
          outputFiles:
            - $SRCROOT/R.generated.swift
    postCompileScripts:
        - name: GoogleServiceInfo
          script: |
            PATH_TO_GOOGLE_PLISTS="${PROJECT_DIR}/Sources/Configs/GoogleServices"
            case "${CONFIGURATION}" in
            "Debug" )
            cp -r "$PATH_TO_GOOGLE_PLISTS/GoogleService-Info-Debug.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist" ;;
            "Staging" )
            cp -r "$PATH_TO_GOOGLE_PLISTS/GoogleService-Info-Staging.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist" ;;
            "Release" )
            cp -r "$PATH_TO_GOOGLE_PLISTS/GoogleService-Info-Release.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist" ;;
            *)
            ;;
            esac
    postBuildScripts:
        - name: Crashlytics
          script: |
            ${PODS_ROOT}/FirebaseCrashlytics/run
          inputFiles:
            - $(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
