name: My Project

options:
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true
  indentWidth: 4
  tabWidth: 4
  bundleIdPrefix: "com.manhpham"

targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources: [Sources]
    settings:
        INFOPLIST_FILE: Sources/Resources/Info.plist
        SWIFT_VERSION: "5.0"
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Resources/MyApp-Bridging-Header.h
        CODE_SIGN_STYLE: "Manual"
    postCompileScripts:
        - name: Swiftlint
          script: |
            if which swiftlint >/dev/null; then
              swiftlint
            else
              echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
            fi
    dependencies:
        - carthage: RxSwift
        - carthage: RxCocoa
        - carthage: RxRelay
        - carthage: Alamofire
        - carthage: Moya
        - carthage: RxMoya
        - carthage: NSObject_Rx
        - carthage: Reusable
        - carthage: Validator
        - carthage: XCGLogger
        - carthage: SVProgressHUD
        - carthage: ObjcExceptionBridging
        - carthage: Differentiator
        - carthage: RxDataSources
